### ISSUE TITLE
Unhandle Exception when zero search results

### ISSUE THREAD

**Issue by rahuldottech** [Fleex255/PolicyPlus#43]
Hey BenN! Here's an error I just found.

Steps to reproduce:
 - Run Policy Plus
 - Search by text for something that'll give you no results
 - Close "Search Results" dialog
 - Go to `Find > Search Results`
 
You'll get an error dialog. Here's the exception text:

```
************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at PolicyPlus.FindResults.FindResults_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

```

**Comment by Fleex255** [comment]
Thanks for the report! This should be fixed in https://github.com/Fleex255/PolicyPlus/commit/531746ac5d2b6d544237b946ecf89aef99ca3a08 - please give the [updated dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) a try.
